# Generated by Django 5.1.2 on 2025-05-08 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=255, unique=True)),
                ('industry', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=255, unique=True)),
                ('phone', models.CharField(max_length=20)),
                ('website', models.URLField(max_length=255)),
                ('address', models.CharField(max_length=255)),
                ('postal_code', models.CharField(max_length=20)),
                ('city', models.CharField(max_length=255)),
                ('employees_count', models.CharField(choices=[('1-10 employés', '1-10 employés'), ('11-50 employés', '11-50 employés'), ('51-200 employés', '51-200 employés'), ('201-500 employés', '201-500 employés'), ('501-1000 employés', '501-1000 employés'), ('1000+ employés', '1000+ employés')], max_length=30)),
                ('contact_person', models.CharField(max_length=255)),
                ('password', models.CharField(max_length=255)),
                ('confirm_password', models.CharField(max_length=255)),
            ],
        ),
    ]
