# Generated by Django 5.1.2 on 2025-05-09 09:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Company', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='confirm_password',
        ),
    ]
